# Uncomment the next line to define a global platform for your project
platform :ios, '10.0' # Adjust this version as needed

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'Firebase/Core' # Firebase Core
  pod 'Firebase/Auth' # Firebase Authentication
  # Add other Firebase pods as needed

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

